env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  angular: true
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: off
